

customer_reviews = [
    """Not sure why the hype. Some good things but a lot of stuff you probably already know if you were not born after 1990. After 1990 math was taught differently and calculators were plentiful. Not saying that’s bad. My main reason for 3 stars is that i couldn’t get the formula for the dare calculation to work every time. I went online and there’s a formula with two more steps that does work. So i found myself doubting whether all the formulas in this book would really work. I spent too long testing out calculations. Ugh. But the stuff that works is a good reminder. Loved multiplying by 11 for instance and stuff like that. Because i’m weird. Most people (adult people) lose their math in the grass but i still like to keep track of my little pet math.""",
    """I bought this book after watching Dr Benjamin's Great Course on video. I can read many times faster than I can watch someone speak so I thought I might get through the information more efficiently by purchasing the book. I also thought there might be additional exercises. Don't get me wrong, the Video course is fun, enlightening and full of real handy tips for mental math. My main complaint is that each chapter is a separate "secret." I haven't even successfully incorporated the last "secret" into my math and there's another one ? If this is to evolve from spectator sport to real world use I need exercises (with answers in the back of the book) so I can practice, practice and practice. The book, alas, follows pretty much the same format as the lectures. There are a few examples, but not many. Each chapter is a separate (often unrelated to the last) tip. So I didn't get any new or additional information, I just got the same information in a different format. I recommend it over the video format because it is less expensive and because you can go as slow or fast as you like""",
    """I first saw Arthur Benjamin on TED and his performance was nothing short of amazing. I was very excited to see a book that explained his methods available on Amazon, so I bought it immediately. I was not disappointed at all to see some hackneyed algorithms repeated in the book. Despite being professionally involved with mathematics as part of my work, and collecting these sorts of math algorithms for ~5o years, there were quite a few I had not seen (or remembered). The book is written in a wonderfully entertaining way that makes it an excellent read; moreover it is easy to learn from. For me at least all of this was spoiled by a ridiculous redundant rant in the so called Chapter Infinity. Apparently M.S. cannot pass up any chance to promulgate his "religion" of skeptic. This final chapter does not belong in this book it is an entirely different subject and is not what I bought the book for. Unfortunately I bought the book in Kindle form so I do not have the option of cutting out the superfluous pages.""",
    """Regardless of the natural gifts we are born with, "Secrets of Mental Math" can show you a technique that may improve your casual use of simple math. I find that todays electronic convenience with cell phones, smart phones and Tablet computers don't allow us the time to dabble in self-made number systems. I find this book interesting as an alternative to the standard math systems taught in todays school and fun to discuss. The author points out several special attitudes about numbers one may never find without his direction. The book is very entertaining and if taken to heart could vault you into the ranks of master simple math guru.""",
    """Whip I really like this book it bothered me that the addition he keeps remindinding u to add right to left but all of his questions start out vertically. I understand because that's the norm... But its was hard to get a natural sense. Of that for the following chapters w o. The original problem being written in that form.. Other than that. Some very neat math tricks!""",
    """The subject is interesting, but the author clearly hasn't proof-read his digital edition. About half the examples are missing - many or most of them are probably jpeg files, which no doubt show up fine on the print edition, but did not carry over to the Kindle edition""",
    """I bought this book in its Kindle version for my PC. I am enjoying it, and happy to see progress in my ability to perform mental calculations. Math was never my strong suit, so this is just what I need. My only negative comment is that the publisher needs to more carefully edit the text. I came upon three typos within the first couple of chapters, and these were errors in operations signs (for example, "+" instead of "x").""",
    """Got through the first two chapters and lost interest. Great tips and tricks but a super boring read and almost feel like you have to study the pages to remember what was said the page before.""",
    """Content is OK, but book is poorly formatted for Kindle. While the text can be enlarged, the forumlae and examples are in a graphics format that leave them minuscule. I had the same problem with another Kindle math book. You'd think Amazon would have resolved this by now."""
    """I have been using this app almost 8 years with 4 to 5 android phones. The app is useful to do office work. However there are more and more bug issues which is not rectified since they appeared. 1. Cannot close & open the app at times 2. Sometimes the keypad comes up with funny laid out with squeezed numbers and symbols in it so make the typing quite difficult 3. Sometimes the cell cannot display what u typed or u need to come down to the phone's typing space to type for each cell.""",
    # """Sometimes annoying I am just editing my document and then boom configuring excel, fetching your files and this take forever. FULL SCREEN, WHY FULL SCREEN? why can't it be done in the background? I am on the move and time is of essence. Disappointed I had to close and open the app lose my unsaved changes.""",
    # """The excel spreadsheet I have saved and access from on my phone keeps freezing and crashing! The page I'm working on will also suddenly fail to fully display and when I try to make an edit, I can't because it totally freezes. I pay Microsoft every month for the extra memory so I don't understand why all of a sudden I'm having so many problems with Excel!""",
    # """I think it's the best app ever, it's fast, appropriate, useable and suitable for high data programs""",
    # """Not keeping în sync the data Not allowing to edit my sheet on Android, on my personal account... Beat the whole porpose of having app in multiple env and lose the control of editing"""
    # """Please add ability to minimize further than minimum. I have a file I previously made on iPad and on my bigger android tablet it's way too big and I can't zoom out further. Thanks!"""
    # """Find myself quite frustrated that I can only download this app to my phone and not my laptop where I do all my document work, but I'll make it work. I'm getting pretty good at work-arounds ;)"""
    # """it's OK app, still not as fast as Google sheets, but u can't expect much. And filters work better on Google sheets. In excel even if u put filters on and drag copy paste, everything outside the filters also gets changed, but Google sheets this never happens, if u hav filters and if u drag copy paste, only the filtered data is changed, so filters work much better in Google sheets. Also excel uses too much internet data as compared to Google sheets.""",
    # """This app was so good before this update. After the current update auto correction and word replace feature is not working properly. Whenever I want to replace the word from English to Hindi it doesn't allow to replace or select the word suggestion. I am unable to use this app now. Please fix this problem as soon as possible.""",
    # """Great app but bad support I love Excel on the desktop but on Android it needs work. Excel used to be able to open and convert XLS files into the newer format of XLSX it doesn't anymore, it just throws an error. I emailed Microsoft Excel support, no reply, problem exists for a month now and no reply and no official mention of not sorting older XLS files anywhere I can see.""",
    # """It's awesome that we can edit excel sheets on our phones, but the mobile app is not very intuitive. Some things are a pain to figure out how to do, for example simply inserting cells, and some thing are clunky, like selecting a cell to edit. It makes sense that the mobile app wouldn't be microsoft's focus, but I think the idea to try and get the ability to do everything on mobile, instead of doing a few things well, was misguided."""
    # """Has suddenly stopped working on my phone and wants a work or school login! But I'm using it personally!""",
    # """Works great but I don't want One Drive to sync and save my files.""",
    # """Only one account?!? I have a home account and outlook is fine with it, but I can't switch to my home account in Excel. Fail""",
    # """The app is wonderful, but the keyboard needs to be updated so we can customise it according to our needs.""",
    # """While it is convenient to have on the go, and while the app functions well for what it is capable of, the functionality is severely limited. An expanded feature set to somewhat pair up with the full application isn't just a "wish list" sort of concept for my uses. When attempting Data Science, Programming, or Biz Administration work I run into walls everywhere. Limited to short lists and brief math it still chafes me, but with patience and extra effort: it just might do the job. 3.2 - 3.5 stars."""

]
